name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65aa00dee79c4af600db9a9c1203b9f73204de6ce1610785afa60928e6c26e01"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
datapack-folder = "resources/common/required"
