name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6662b2552de6741786653cd2d8e286e9d834c2acc6e4356b924fdb5d5f52e10e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
datapack-folder = "resources/common/required"
