name = "Polymania"
author = "Patbox"
version = "<MODPACKVERSION>"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce582f8dc6a9410721a696044a0d7385bc3ff1bf3929639780335288b16f9ba1"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
datapack-folder = "resources/common/required"
