[links]
	"known_server_link.website" = "https://modrinth.com/modpack/polymania"
	"known_server_link.report_bug" = "https://github.com/Patbox/polymania/issues"
	"known_server_link.community" = "https://pb4.eu/discord"
