[links]
	"custom_server_link.website" = "https://modrinth.com/modpack/polymania"
	"custom_server_link.discord" = "https://pb4.eu/discord"
	"known_server_link.report_bug" = "https://github.com/Patbox/polymania/issues"
