import java.nio.file.Files

plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
}

version = Files.readString(file("../version.txt").toPath())
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	maven {url = 'https://maven.nucleoid.xyz' }
	maven {url = 'https://api.modrinth.com/maven' }
	maven { url 'https://maven.kneelawk.com/releases/' }
}


dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	implementation "eu.pb4:polymer-core:${project.polymer_version}"
	implementation "eu.pb4:polymer-blocks:${project.polymer_version}"
	implementation "eu.pb4:polymer-resource-pack:${project.polymer_version}"
	implementation "eu.pb4:polymer-resource-pack-extras:${project.polymer_version}"
	implementation "eu.pb4:polymer-autohost:${project.polymer_version}"
	implementation "eu.pb4:polymer-virtual-entity:${project.polymer_version}"
	implementation "eu.pb4:polymer-sound-patcher:${project.polymer_version}"

	implementation 'eu.pb4:booklet:0.3.2+26.2'
	implementation include('eu.pb4:map-canvas-api:0.9.0+26.2')
	implementation include('eu.pb4:common-protection-api:2.0.0')
	implementation include('eu.pb4:sidebar-api:0.6.0+26.1')
	implementation include('eu.pb4:sgui:2.1.0+26.2')
	implementation include('eu.pb4:factorytools:0.11.2+26.2')
	implementation include("eu.pb4:placeholder-api:3.1.0-beta.1+26.2")
	implementation 'xyz.nucleoid:server-translations-api:3.1.0+26.2'
	implementation include('com.kneelawk.graphlib:graphlib-core-fabric:2.0.3-beta.0.matti+26.2')


	// blahaj replushed
	implementation "maven.modrinth:5bb5rG4b:3Hf4wcFz"

	//modImplementation include('com.kneelawk.graphlib:graphlib-core-fabric:2.0.3-beta.1+1.21.5')
	//modImplementation 'com.kneelawk.graphlib:graphlib-core-fabric:2.0.3-beta.0.patbox+1.21.11'
	//modImplementation 'maven.modrinth:polyfactory:0.10.3+1.21.11'

}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}